---
name: Site Lint

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install tools
        run: |
          cargo install minijinja-cli
          sudo apt install nodejs npm php

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Set up projects directory
        run: ./setup.bash

      - name: Install linkchecker
        run: pip3 install --user linkchecker

      - name: Run site
        run: php -S 127.0.0.1:8000&

      - name: Check for 404's
        run: sleep 1 && linkchecker http://127.0.0.1:8000
